name: Traitors
version: ${project.version}
main: com.github.drakepork.traitors.TraitorsMain
api-version: 1.16
depend: [CMI, TokenManager]
authors: [DrakePork]
description: Wham
commands:
  traitor:
    description: Traitor Stuff
    usage: /<command>
    permission: royalasylum.traitor
    permission-message: §4Error:§c You do not have permission to execute this command...
  traitortrack:
    description: Traitor Stuff
    usage: /<command>
    permission: royalasylum.traitor.gui
    permission-message: §4Error:§c You do not have permission to execute this command...
  traitorcheck:
    description: Traitor Stuff
    usage: /<command>
    permission: royalasylum.traitor.check
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:
  royalasylum.traitor:
    description: Gives you access to /traitor commands
  royalasylum.traitor.gui:
    description: Gives you access to /traitortrack command
  royalasylum.traitor.check:
    description: Gives you access to /traitorcheck command